apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flower-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/nanuchi/argocd-app-config.git
    targetRevision: HEAD
    path: flower
  destination:
    server: https://kubernetes.default.svc
    namespace: my_apps_dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true